### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Wen-Binghui** [Wen-Binghui/ML3D_AtlasNet_HumanBodyDataset#1]
- [x] utlis.gen_pointclouds 可以调输出点数；
- [x] number_points 改大再训练一次；
- [x] 改一下create_dataset 手动产生overfit （2个obj模型）
- [x] 面部角度改到全部是正脸照片，角度变化很小；
- [x] #2
- [x] 增加fit的mesh个数，防止overfiting

**Comment by Wen-Binghui** [comment]
done
